
function(extract_git_hash)
	if (WIN32)
		execute_process(COMMAND cmd /C "git -C ${CMAKE_CURRENT_SOURCE_DIR} rev-parse HEAD" OUTPUT_VARIABLE VALUE OUTPUT_STRIP_TRAILING_WHITESPACE)
	else ()
		execute_process(COMMAND bash -c "git -C ${CMAKE_CURRENT_SOURCE_DIR} rev-parse HEAD" OUTPUT_VARIABLE VALUE OUTPUT_STRIP_TRAILING_WHITESPACE)
	endif ()
	set(GIT_HASH "${VALUE}" PARENT_SCOPE)
endfunction()

function(create_guid)
	extract_git_hash()
	string(SUBSTRING ${GIT_HASH} 0 8 S1)
	string(SUBSTRING ${GIT_HASH} 8 4 S2)
	string(SUBSTRING ${GIT_HASH} 12 4 S3)
	string(SUBSTRING ${GIT_HASH} 16 4 S4)
	string(SUBSTRING ${GIT_HASH} 20 12 S5)
	set(GUID "${S1}-${S2}-${S3}-${S4}-${S5}" PARENT_SCOPE)
endfunction()
