name: CI
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 55 19 * * 3 # 19:55 every wednesday

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: 'windows'
          - os: ubuntu-latest
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: GCC version on Linux
        shell: bash
        run: g++ --version
        if: runner.os == 'Linux'

      - name: Set C++ VCPKG_ROOT
        shell: bash
        run: echo VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"; cat "$GITHUB_ENV"

# Debug build
      - name: Run CMake Debug with manifest mode vcpkg
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build_debug -DUSE_WIX_GENERATOR=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Compile Debug binaries
        shell: bash
        run: cmake --build build_debug --config Debug

      - name: Run Debug tests
        shell: bash
        run: |
          ctest --rerun-failed --output-on-failure --test-dir build_debug/VinlandVikings_Test

# Release build
      - name: Run CMake Release with manifest mode vcpkg
        shell: bash
        run: cmake --preset=${{ matrix.preset }} -B build_release -DUSE_WIX_GENERATOR=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1

      - name: Compile Release binaries
        shell: bash
        run: cmake --build build_release --config Release

      - name: Run Release tests
        shell: bash
        run: |
          ctest --rerun-failed --output-on-failure --test-dir build_release/VinlandVikings_Test
